allowBuilds:
  core-js: false

overrides:
  '@babel/plugin-transform-modules-systemjs': '7.29.4'
  'express-rate-limit': '8.5.1'
  'fast-uri': '3.1.8'
  'hono': '4.13.13'
  'ip-address': '10.7.3'
  'serialize-javascript': '^7.0.5'

patchedDependencies:
  cmdk@1.1.1: patches/cmdk@1.1.1.patch
