import { LegalPage, LegalSections } from '@/components/legal/LegalPage'
import { legalToc, type LegalSection } from '@/lib/legalSections'

const LAST_UPDATED = 'May 2, 2026'

const sections: LegalSection[] = [
  {
    title: '1. Acceptance of Terms',
    content:
      'By accessing or using Ledger (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. We reserve the right to update these terms at any time; continued use of the Service after changes constitutes acceptance.',
  },
  {
    title: '2. Description of Service',
    content:
      'Ledger is a personal finance tracking application that allows you to record, categorise, and analyse your financial transactions. The Service is provided for personal, non-commercial use only. It is not a financial institution, bank, or regulated financial service.',
  },
  {
    title: '3. Eligibility',
    content: [
      'You must be at least 13 years old to use the Service.',
      'You must provide accurate and complete information when creating your account.',
      'You are responsible for maintaining the security of your account credentials.',
      'One person may not create multiple accounts; each account must represent a single individual.',
    ],
  },
  {
    title: '4. User Responsibilities',
    content: [
      'You are solely responsible for the accuracy and completeness of the financial data you enter.',
      'You must not use the Service for any unlawful purpose or in any way that violates applicable regulations.',
      'You must not attempt to gain unauthorised access to other users\' data or any part of the Service infrastructure.',
      'You must not reverse-engineer, decompile, or attempt to extract the source code of the Service.',
    ],
  },
  {
    title: '5. Intellectual Property',
    content:
      'All content, design, code, and materials comprising the Service are the intellectual property of Ledger and its contributors. You are granted a limited, non-exclusive, non-transferable licence to use the Service for personal purposes. You may not reproduce, distribute, or create derivative works without prior written consent.',
  },
  {
    title: '6. Data & Privacy',
    content:
      'Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the collection and use of your data as described in the Privacy Policy.',
  },
  {
    title: '7. Disclaimers',
    content: [
      'The Service is provided "as is" and "as available" without warranties of any kind, express or implied.',
      'Ledger does not warrant that the Service will be uninterrupted, error-free, or free of harmful components.',
      'The financial insights and reports generated by the Service are for informational purposes only and do not constitute financial advice.',
      'Ledger is not responsible for any financial decisions you make based on data displayed in the Service.',
    ],
  },
  {
    title: '8. Limitation of Liability',
    content:
      'To the fullest extent permitted by applicable law, Ledger shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Service — including but not limited to loss of data, loss of revenue, or loss of profits.',
  },
  {
    title: '9. Termination',
    content:
      'You may stop using the Service at any time. We reserve the right to suspend or terminate your access if you violate these Terms, engage in fraudulent activity, or if we discontinue the Service. Upon termination, your right to access the Service ceases immediately.',
  },
  {
    title: '10. Governing Law',
    content:
      'These Terms shall be governed by and construed in accordance with applicable laws. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the relevant courts, unless otherwise required by local consumer protection laws.',
  },
  {
    title: '11. Changes to Terms',
    content:
      'We may revise these Terms at any time by updating this page. The "Last updated" date at the top will reflect the most recent revision. Material changes will be communicated via the application. Your continued use after any changes constitutes acceptance of the new Terms.',
  },
  {
    title: '12. Contact',
    content:
      'If you have any questions about these Terms of Service, please reach out through the Settings page or the contact information provided in the application.',
  },
]

export default function TermsOfServicePage() {
  return (
    <LegalPage
      current="terms"
      title="Terms of Service"
      lastUpdated={LAST_UPDATED}
      intro={
        <p>
          Please read these Terms of Service carefully before using Ledger. They govern your access to
          and use of the application and constitute a binding legal agreement between you and Ledger.
        </p>
      }
      toc={legalToc(sections)}
    >
      <LegalSections sections={sections} />
    </LegalPage>
  )
}
