import { Link } from 'react-router-dom'
import { ArrowLeft, ScrollText } from 'lucide-react'
import { Separator } from '@/components/ui/separator'

const LAST_UPDATED = 'May 2, 2026'

interface Section {
  title: string
  content: string | string[]
}

const sections: Section[] = [
  {
    title: '1. Acceptance of Terms',
    content:
      'By accessing or using Ledger (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. We reserve the right to update these terms at any time; continued use of the Service after changes constitutes acceptance.',
  },
  {
    title: '2. Description of Service',
    content:
      'Ledger is a personal finance tracking application that allows you to record, categorise, and analyse your financial transactions. The Service is provided for personal, non-commercial use only. It is not a financial institution, bank, or regulated financial service.',
  },
  {
    title: '3. Eligibility',
    content: [
      'You must be at least 13 years old to use the Service.',
      'You must provide accurate and complete information when creating your account.',
      'You are responsible for maintaining the security of your account credentials.',
      'One person may not create multiple accounts; each account must represent a single individual.',
    ],
  },
  {
    title: '4. User Responsibilities',
    content: [
      'You are solely responsible for the accuracy and completeness of the financial data you enter.',
      'You must not use the Service for any unlawful purpose or in any way that violates applicable regulations.',
      'You must not attempt to gain unauthorised access to other users\' data or any part of the Service infrastructure.',
      'You must not reverse-engineer, decompile, or attempt to extract the source code of the Service.',
    ],
  },
  {
    title: '5. Intellectual Property',
    content:
      'All content, design, code, and materials comprising the Service are the intellectual property of Ledger and its contributors. You are granted a limited, non-exclusive, non-transferable licence to use the Service for personal purposes. You may not reproduce, distribute, or create derivative works without prior written consent.',
  },
  {
    title: '6. Data & Privacy',
    content:
      'Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the collection and use of your data as described in the Privacy Policy.',
  },
  {
    title: '7. Disclaimers',
    content: [
      'The Service is provided "as is" and "as available" without warranties of any kind, express or implied.',
      'Ledger does not warrant that the Service will be uninterrupted, error-free, or free of harmful components.',
      'The financial insights and reports generated by the Service are for informational purposes only and do not constitute financial advice.',
      'Ledger is not responsible for any financial decisions you make based on data displayed in the Service.',
    ],
  },
  {
    title: '8. Limitation of Liability',
    content:
      'To the fullest extent permitted by applicable law, Ledger shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Service — including but not limited to loss of data, loss of revenue, or loss of profits.',
  },
  {
    title: '9. Termination',
    content:
      'You may stop using the Service at any time. We reserve the right to suspend or terminate your access if you violate these Terms, engage in fraudulent activity, or if we discontinue the Service. Upon termination, your right to access the Service ceases immediately.',
  },
  {
    title: '10. Governing Law',
    content:
      'These Terms shall be governed by and construed in accordance with applicable laws. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the relevant courts, unless otherwise required by local consumer protection laws.',
  },
  {
    title: '11. Changes to Terms',
    content:
      'We may revise these Terms at any time by updating this page. The "Last updated" date at the top will reflect the most recent revision. Material changes will be communicated via the application. Your continued use after any changes constitutes acceptance of the new Terms.',
  },
  {
    title: '12. Contact',
    content:
      'If you have any questions about these Terms of Service, please reach out through the Settings page or the contact information provided in the application.',
  },
]

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden">

      {/* ── Atmospheric background (mirrors LoginPage) ── */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-175 h-125 rounded-full"
          style={{ background: 'radial-gradient(ellipse, color-mix(in srgb, var(--primary) 4%, transparent) 0%, transparent 70%)' }}
        />
        <div
          className="absolute inset-0 opacity-[0.03]"
          style={{
            backgroundImage: 'radial-gradient(circle, var(--foreground) 1px, transparent 1px)',
            backgroundSize: '40px 40px',
          }}
        />
        <div className="absolute -top-40 -left-40 w-120 h-120 rounded-full border border-primary/5" />
        <div className="absolute -bottom-48 -right-48 w-125 h-125 rounded-full border border-primary/5" />
      </div>

      <div className="relative z-10 max-w-3xl mx-auto px-4 py-12 md:py-16">

        {/* ── Back link ── */}
        <Link
          to="/login"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-10 group"
        >
          <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-0.5" />
          Back
        </Link>

        {/* ── Header ── */}
        <div className="mb-10">
          <div className="flex items-center gap-3 mb-4">
            <div
              className="flex items-center justify-center w-10 h-10 rounded-xl"
              style={{ background: 'color-mix(in srgb, var(--primary) 12%, transparent)' }}
            >
              <ScrollText className="w-5 h-5" style={{ color: 'var(--primary)' }} />
            </div>
            <div>
              <h1
                className="text-3xl md:text-4xl font-bold tracking-tight"
                style={{ fontFamily: "'Playfair Display', serif" }}
              >
                Terms of Service
              </h1>
            </div>
          </div>
          <p className="text-sm text-muted-foreground">
            Last updated: <span className="font-medium text-foreground">{LAST_UPDATED}</span>
          </p>
          <p className="mt-4 text-muted-foreground leading-relaxed max-w-2xl">
            Please read these Terms of Service carefully before using Ledger. They govern your access
            to and use of the application and constitute a binding legal agreement between you and Ledger.
          </p>
        </div>

        <Separator className="mb-10 opacity-50" />

        {/* ── Sections ── */}
        <div className="space-y-8">
          {sections.map((section) => (
            <section key={section.title}>
              <h2
                className="text-base font-semibold mb-3"
                style={{ color: 'var(--primary)' }}
              >
                {section.title}
              </h2>
              {Array.isArray(section.content) ? (
                <ul className="space-y-2">
                  {section.content.map((item, i) => (
                    <li key={i} className="flex gap-3 text-sm text-muted-foreground leading-relaxed">
                      <span
                        className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full"
                        style={{ background: 'color-mix(in srgb, var(--primary) 60%, transparent)' }}
                      />
                      {item}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-sm text-muted-foreground leading-relaxed">{section.content}</p>
              )}
            </section>
          ))}
        </div>

        <Separator className="my-10 opacity-50" />

        {/* ── Privacy Policy link ── */}
        <div
          className="rounded-xl border p-5 mb-10 flex gap-4"
          style={{
            borderColor: 'color-mix(in srgb, var(--primary) 25%, transparent)',
            background: 'color-mix(in srgb, var(--primary) 4%, transparent)',
          }}
        >
          <ScrollText
            className="mt-0.5 shrink-0 w-5 h-5"
            style={{ color: 'var(--primary)' }}
          />
          <div>
            <p className="text-sm font-semibold text-foreground mb-1">Also see our Privacy Policy</p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              For information on how we collect, use, and protect your personal data, visit our{' '}
              <Link to="/privacy" className="underline underline-offset-2 hover:text-foreground transition-colors">
                Privacy Policy
              </Link>{' '}
              page.
            </p>
          </div>
        </div>

        {/* ── Footer ── */}
        <p className="text-center text-[0.6875rem] text-muted-foreground/50">
          © {new Date().getFullYear()} Ledger. All rights reserved.
        </p>
      </div>
    </div>
  )
}
